$background = 000605
$onBackground = d7e6e2
$surface = 000605
$surfaceDim = 000605
$surfaceBright = 0b1211
$surfaceContainerLowest = 000403
$surfaceContainerLow = 020908
$surfaceContainer = 030a09
$surfaceContainerHigh = 070e0d
$surfaceContainerHighest = 0a1110
$onSurface = d7e6e2
$surfaceVariant = 071614
$onSurfaceVariant = b1ccc8
$outline = 7b9692
$outlineVariant = 324b48
$inverseSurface = d7e6e2
$inverseOnSurface = 263331
$shadow = 000000
$scrim = 000000
$surfaceTint = 0e2f02
$primary = 9cd67e
$primaryDim = bffc9f
$onPrimary = 103900
$primaryContainer = 1f5107
$onPrimaryContainer = b7f397
$inversePrimary = 376a20
$primaryFixed = b7f397
$primaryFixedDim = 9cd67e
$onPrimaryFixed = 062100
$onPrimaryFixedVariant = 1f5107
$secondary = a9d291
$secondaryDim = c5efab
$onSecondary = 173807
$secondaryContainer = 2d4f1d
$onSecondaryContainer = c5efab
$secondaryFixed = c5efab
$secondaryFixedDim = a9d291
$onSecondaryFixed = 062100
$onSecondaryFixedVariant = 2d4f1d
$tertiary = 81d5cc
$tertiaryDim = a8fdf3
$onTertiary = 003733
$tertiaryContainer = 00504a
$onTertiaryContainer = 9df2e8
$tertiaryFixed = 9df2e8
$tertiaryFixedDim = 81d5cc
$onTertiaryFixed = 00201d
$onTertiaryFixedVariant = 00504a
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 4f8436
$secondaryPaletteKeyColor = 5c8149
$tertiaryPaletteKeyColor = 2a847c
$neutralPaletteKeyColor = 6c7a78
$neutralVariantPaletteKeyColor = 627c78
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 4f8436
$secondary_paletteKeyColor = 5c8149
$tertiary_paletteKeyColor = 2a847c
$neutral_paletteKeyColor = 6c7a78
$neutral_variant_paletteKeyColor = 627c78
$term0 = 080808
$term1 = 8d9800
$term2 = a9db74
$term3 = cff383
$term4 = 89b58c
$term5 = c6a844
$term6 = a8d695
$term7 = d6dac5
$term8 = a2a494
$term9 = a3b200
$term10 = b3ef77
$term11 = e1ffa7
$term12 = b0c8a9
$term13 = cec06b
$term14 = b8e99e
$term15 = ffffff
$rosewater = f4f2e3
$flamingo = e4e4c4
$pink = ffd79d
$mauve = 5bd0df
$red = c5b542
$maroon = c6c177
$peach = c7d48e
$yellow = e9f7cb
$green = baeea3
$teal = b9edb6
$sky = aceab5
$sapphire = 8dd7a3
$blue = 72cfa0
$lavender = 89dcc6
$klink = 389867
$klinkSelection = 389867
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 878e00
$knegativeSelection = 878e00
$kneutral = 9bb600
$kneutralSelection = 9bb600
$kpositive = 68bc55
$kpositiveSelection = 68bc55
$text = d7e6e2
$subtext1 = b1ccc8
$subtext0 = 7b9692
$overlay2 = 161e1d
$overlay1 = 121b19
$overlay0 = 0f1716
$surface2 = 0b1412
$surface1 = 060f0e
$surface0 = 010807
$base = 000100
$mantle = 000100
$crust = 000100
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
