$primary_paletteKeyColor = a6627e
$secondary_paletteKeyColor = 8d6f79
$tertiary_paletteKeyColor = 9a6e4e
$neutral_paletteKeyColor = 807477
$neutral_variant_paletteKeyColor = 837378
$background = 070305
$onBackground = eedfe2
$surface = 070305
$surfaceDim = 070305
$surfaceBright = 121010
$surfaceContainerLowest = 050203
$surfaceContainerLow = 0b0608
$surfaceContainer = 0d0709
$surfaceContainerHigh = 0f0c0c
$surfaceContainerHighest = 120e0f
$onSurface = eedfe2
$surfaceVariant = 171213
$onSurfaceVariant = d5c2c7
$inverseSurface = eedfe2
$inverseOnSurface = 372e31
$outline = 9d8c91
$outlineVariant = 514347
$shadow = 000000
$scrim = 000000
$surfaceTint = 3e1e2b
$primary = ffb0ce
$onPrimary = 531d36
$primaryContainer = 6e334d
$onPrimaryContainer = ffd9e5
$inversePrimary = 8a4a65
$secondary = e1bdc9
$onSecondary = 412a33
$secondaryContainer = 5a3f49
$onSecondaryContainer = ffd9e5
$tertiary = f1bc96
$onTertiary = 49290e
$tertiaryContainer = b68765
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd9e5
$primaryFixedDim = ffb0ce
$onPrimaryFixed = 390721
$onPrimaryFixedVariant = 6e334d
$secondaryFixed = ffd9e5
$secondaryFixedDim = e1bdc9
$onSecondaryFixed = 2a151e
$onSecondaryFixedVariant = 5a3f49
$tertiaryFixed = ffdcc5
$tertiaryFixedDim = f1bc96
$onTertiaryFixed = 301400
$onTertiaryFixedVariant = 633e22
$term0 = 080808
$term1 = ff4a92
$term2 = ffbbba
$term3 = ffdee0
$term4 = b3a2d5
$term5 = e890b4
$term6 = ffba93
$term7 = eed1d3
$term8 = b39e9f
$term9 = ff80a8
$term10 = ffd3d1
$term11 = fff1f1
$term12 = dcbc93
$term13 = f7a8c5
$term14 = ffd1c0
$term15 = ffffff
$rosewater = ffedf0
$flamingo = fbd9e2
$pink = ffd0e3
$mauve = fda5d9
$red = fb95bc
$maroon = f2aac2
$peach = ffbcc8
$yellow = ffeded
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = f2b2f2
$blue = f1a3e2
$lavender = fdb7e8
$klink = b66eaf
$klinkSelection = b56eaf
$kvisited = c35d99
$kvisitedSelection = c35d99
$knegative = e74f8d
$knegativeSelection = e74f8d
$kneutral = ff84a1
$kneutralSelection = ff84a1
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = eedfe2
$subtext1 = d5c2c7
$subtext0 = 9d8c91
$overlay2 = 1c1c1c
$overlay1 = 1a1819
$overlay0 = 171516
$surface2 = 141112
$surface1 = 110c0e
$surface0 = 090507
$base = 010001
$mantle = 010001
$crust = 010001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
