########## hyprland.conf ##########
monitor = eDP-1, 1920x1200@165, 0x0, 1.25
# monitor = eDP-1, 1920x1200@60, 0x0, 1.25

########## env.conf ##########
env = XDG_MENU_PREFIX, arch-
env = QT_SCALE_FACTOR_ROUNDING_POLICY, RoundPreferFloor

########## general.conf ##########
general {
    layout = dwindle
    # layout = master
    # layout = scrolling
}

########## gestures.conf ##########
gestures {
    workspace_swipe_distance = 400
    workspace_swipe_cancel_ratio = 0.15
    workspace_swipe_min_speed_to_force = 5
    workspace_swipe_direction_lock = false
    workspace_swipe_direction_lock_threshold = 10
    workspace_swipe_create_new = true
}

########## input.conf ##########
input {
    numlock_by_default = true

    accel_profile = flat
    sensitivity = 0.5

    kb_options = caps:escape
}
binds {
    scroll_event_delay = 0
}
cursor {
    no_hardware_cursors = true
}

########## keybinds.conf ##########
# Apps
bind = Super, H, exec, app2unit -- heroic
bind = Super+Alt, W, exec, app2unit -- $browserAlt
bind = Ctrl+Alt, Tab, exec, app2unit -- pavucontrol
bind = Super, G, exec, ~/.config/quickshell/game-launcher/toggle.sh
bind = , XF86Launch7, exec, DAMX
# Utilities
bind = Super+Shift, S, global, caelestia:screenshotClip 
# bind = Super+Shift, S, exec, grim -g "$(slurp)" - | wl-copy
bind = Super+Shift, T, exec, ~/.local/bin/ocrshot

# Night light
bind = Super+Shift, N, exec, pkill hyprsunset || hyprsunset --temperature 9000
bind = Super+Shift+Alt, N, exec, pkill hyprsunset || hyprsunset --temperature 3500

########## misc.conf ##########
xwayland {
    force_zero_scaling = true
}
render {
    direct_scanout = true
}

########## rules.conf ##########
windowrule = workspace special:music, match:class com.github.neithern.g4music|io.bassi.Amberol|org.strawberrymusicplayer.strawberry|feishin|Spotify|Supersonic|Cider|com.github.th_ch.youtube_music|Plexamp
windowrule = workspace special:communication, match:class discord|ferdium|equibop|vesktop|whatsapp

########## scrolling.conf ##########
scrolling {
    direction = right
}

########## Quickshell TAB Overview ##########
bind = Super, TAB, exec, qs ipc -c overview call overview toggle
exec-once = qs -c overview

layerrule = blur false, match:namespace quickshell:overview-blur
layerrule = ignore_alpha 0.2, match:namespace quickshell:overview-blur

########## Pywal Script ##########
exec-once = ~/.config/hypr/scripts/watch-caelestia-firefox.sh
