## variables.conf

# Apps
$terminal = foot
$browser = firefox
$editor = google-chrome-stable
$browserAlt = zen-browser
$fileExplorer = dolphin

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 1
$workspaceSwipeFingers = 3
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = true
$blurPopups = true
$blurInputMethods = true
$blurSize = 7
$blurPasses = 2
$blurXray = true

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3

# Gaps
$workspaceGaps = 10
$windowGapsIn = 1
$windowGapsOut = 0
$singleWindowGapsOut = 0

# Window styling
$windowOpacity = 1
$windowRounding = 15
$windowBorderSize = 2

# Misc
$volumeStep = 2 # In percent
$cursorTheme = phinger-cursors-light
$cursorSize = 24 

# Window actions
$kbCloseWindow = Super, C

# Apps
$kbTerminal = Super, Q
$kbBrowser = Super, W
$kbEditor = Super, A
$kbFileExplorer = Super, E
