# Night light
bind = Super+Shift, N, exec, pkill hyprsunset || hyprsunset --temperature 9000
bind = Super+Shift+Alt, N, exec, pkill hyprsunset || hyprsunset --temperature 3500















# Pywal script
exec-once = ~/.config/hypr/scripts/watch-caelestia-firefox.sh
