input {
    kb_layout = us
    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 35

    accel_profile = flat
    sensitivity = 0.5
 
    focus_on_close = 1

    kb_options = caps:escape

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

binds {
    scroll_event_delay = 0
}

cursor {
    hotspot_padding = 1
    no_hardware_cursors = true
}

